### ISSUE TITLE
License Issues

### ISSUE THREAD

**Issue by Un1matr1x** [Warsaalk/OGetIt#1]
Hi,

the license you choose is some kind of a problem, if you want to integrade your package into another project, f.e. a phpBB-Extension, which requrieres to be GPL2 (to become offical released on phpbb.com with security-checks and so on). Even [Bootstraps](https://github.com/twbs/bootstrap) had [such a discussion](https://github.com/twbs/bootstrap/issues/2054), so I would ask / recoment to change your license.

At this point it would be easy for you to do so, since you're the only contributer so far, if you won't do such a change by now (or want to be able to make such changes in the future without any issues) you might want to use something like: https://www.clahub.com/

best regards

€dit: if you don't want to change the license you could also dual licensing, like gpl & mit f.e. - so a developer can choose what fits his needs

**Comment by klaasvp** [comment]
Hi,

LGPLv3 is indeed not compatible with GPL2.
I suppose you're planning to use my library in one of your phpBB-extensions?

Regards,
Klaas

**Comment by Un1matr1x** [comment]
Hi,

I was thinking about usinge your library in my oGame-Ext f.e. to show the Espionage-Reports.

Since I'm planning to publish this ext via phpbb.com via their extension-database I have to be conform with:
https://www.phpbb.com/extensions/rules-and-policies/validation-policy/#licenses

Regards,
Falk

**Comment by klaasvp** [comment]
Hi,

I think dual licensing wouldn't be necessary and it also isn't relevant for this project.
I did some license research again and am willing to change the license from LGPLv3 to LGPLv2.1.
LGPLv2.1 library software can be used in code released under GPLv2 without any problems.
http://www.gnu.org/licenses/gpl-faq.html#AllCompatibility

Regards,
Klaas

**Comment by Un1matr1x** [comment]
Hi,

I like to hear this, the idea about dual licensing would have been another way, if you wound't be willing to change your license.

Thank & Regards,
Falk
